"""Chunk-level metadata produced during the chunking process.

``ChunkMetadata`` is generated and populated by a chunking strategy
for each resulting chunk.  It complements ``KnowledgeMetadata`` by
capturing positional and structural information about *how* the
chunk was produced.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ChunkMetadata:
    """Metadata generated by the chunking process for a single chunk.

    Attributes:
        document_id: Identifier of the source document (if known).
        chunk_index: Position of this chunk among all chunks produced
            from the source (0-based).
        character_start: Character offset of this chunk within the source
            document (inclusive).
        character_end: Character offset of this chunk within the source
            document (exclusive).
        word_count: Number of words in this chunk.
        line_count: Number of lines in this chunk.
        strategy: Name of the strategy that produced this chunk.
        created_at: Unix timestamp when the chunk was created.
        chunk_size: The chunk_size parameter used when chunking.
        overlap: The chunk_overlap parameter used when chunking.
        is_partial: ``True`` if the chunk was truncated by ``max_chunks``
            or other early-termination condition.
        token_count: Approximate token count (populated after
            estimation).  ``-1`` means not yet computed.
    """

    document_id: str = ""
    chunk_index: int = 0
    character_start: int = -1
    character_end: int = -1
    word_count: int = 0
    line_count: int = 0
    strategy: str = ""
    created_at: float = 0.0
    chunk_size: int = 0
    overlap: int = 0
    is_partial: bool = False
    token_count: int = -1
