"""Chunk-level metadata produced during the chunking process.

``ChunkMetadata`` is generated and populated by a chunking strategy
for each resulting chunk.  It complements ``KnowledgeMetadata`` by
capturing positional and structural information about *how* the
chunk was produced.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class ChunkMetadata:
    """Metadata generated by the chunking process for a single chunk.

    Attributes:
        start_char: Character offset of this chunk within the source
            document (inclusive).
        end_char: Character offset of this chunk within the source
            document (exclusive).
        index: Position of this chunk among all chunks produced from
            the source (0-based).
        strategy: Name of the strategy that produced this chunk.
        chunk_size: The chunk_size parameter used when chunking.
        overlap: The chunk_overlap parameter used when chunking.
        is_partial: ``True`` if the chunk was truncated by ``max_chunks``
            or other early-termination condition.
        token_count: Approximate token count (populated after
            estimation).  ``-1`` means not yet computed.
    """

    start_char: int = -1
    end_char: int = -1
    index: int = 0
    strategy: str = ""
    chunk_size: int = 0
    overlap: int = 0
    is_partial: bool = False
    token_count: int = -1
